/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AovReadmeRouteImport } from './routes/aov-readme'
import { Route as IndexRouteImport } from './routes/index'

const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AovReadmeRoute = AovReadmeRouteImport.update({
  id: '/aov-readme',
  path: '/aov-readme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aov-readme': typeof AovReadmeRoute
  '/dashboard': typeof DashboardRoute
  '/readme': typeof ReadmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aov-readme': typeof AovReadmeRoute
  '/dashboard': typeof DashboardRoute
  '/readme': typeof ReadmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aov-readme': typeof AovReadmeRoute
  '/dashboard': typeof DashboardRoute
  '/readme': typeof ReadmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aov-readme' | '/dashboard' | '/readme'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aov-readme' | '/dashboard' | '/readme'
  id: '__root__' | '/' | '/aov-readme' | '/dashboard' | '/readme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AovReadmeRoute: typeof AovReadmeRoute
  DashboardRoute: typeof DashboardRoute
  ReadmeRoute: typeof ReadmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aov-readme': {
      id: '/aov-readme'
      path: '/aov-readme'
      fullPath: '/aov-readme'
      preLoaderRoute: typeof AovReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AovReadmeRoute: AovReadmeRoute,
  DashboardRoute: DashboardRoute,
  ReadmeRoute: ReadmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
